In [40]:
import pandas as pd
import numpy as np
import datetime


# File to Load (Remember to Change These)
file_to_load = "resources/Datamyne_toothfish_monthly_2020.csv"

# Read Purchasing File and store into Pandas data frame
#monthly_data = pd.read_csv(file_to_load)


monthly_data = pd.read_csv(file_to_load)

In [41]:
monthly_data

,Date,Bill of lading Nbr.,Consignee Declared,Shipper Declared,Short Container Description,Country of Origin,Port of Arrival,Final Destination,Weight,Weight Unit,Quantity,Quantity Unit,Container,Pieces,Description,Harmonized,Marks & Numbers,HS
0,2/11/2020,SUDU59BUE026704X,STAVIS SEAFOOD LLC,EMPRESA PESQUERA DE LA PATAGONIA Y,281-BAGS-FROZEN PATAGONIAN TOOTHFISH HGT IWP 0...,ARGENTINA,"NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY",NOT DECLARED,"20,609.00",KG,842,BAG,MNBU3923073,842,281-BAGS-FROZEN PATAGONIAN TOOTHFISH HGT IWP 0...,30383.0,PESANTAR,30383
1,2/11/2020,SUDU59BUE026679X,STAVIS SEAFOOD LLC,EMPRESA PESQUERA DE LA PATAGONIA Y,285-BAGS-FROZEN PATAGONIAN TOOTHFISH HGT IWP 0...,ARGENTINA,"NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY",NOT DECLARED,"21,540.00",KG,870,BAG,SUDU6076487,870,285-BAGS-FROZEN PATAGONIAN TOOTHFISH HGT IWP 0...,30383.0,PESANTAR,30383
2,2/11/2020,SUDU59BUE026512X,mark foods,PESANTAR,139-BAGS-FROZEN PATAGONIAN TOOTHFISH HGT IWP 0...,ARGENTINA,"NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY",NOT DECLARED,"22,352.00",KG,998,BAG,MWCU6910169,998,139-BAGS-FROZEN PATAGONIAN TOOTHFISH HGT IWP 0...,30383.0,PESANTAR,30383
3,2/10/2020,MEDUCH355884,SABANAMAR INTERNATIONAL L.L.C.,ISAM CHILE S.A.,"146 CARTONSFROZEN CHILEAN SEABASS HGT IWP, VA ...",CHILE,"NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY",NOT DECLARED,"18,648.00",K,"1,576.00",CTN,TRIU8926367,"1,576","146 CARTONSFROZEN CHILEAN SEABASS HGT IWP, VA ...",NaN,NO MARKS NO MARKS NO MARKS NO MARKS NO MARKS,30481
4,2/10/2020,SUDUB0SCL000225X,DEEP BLUE FISHERY LLC,PROYECTA CORP S.A.,"238CARTONS: 4.544,15KGS. NET WEIGHT CHILEAN SE...",CHILE,"PORT EVERGLADES,FL",NOT DECLARED,"5,100.00",KG,238,CTN,MNBU3295850,238,"238CARTONS: 4.544,15KGS. NET WEIGHT CHILEAN SE...",30485.0,NO MARKS,30485
5,2/6/2020,SUDU59BUE025610X,mark foods,ESTREMAR SA,30 BOXES OF FROZEN PATAGONIAN TOOTHFISH HGT 10...,ARGENTINA,"PORT EVERGLADES,FL",NOT DECLARED,"22,809.00",KG,65,PKG,MSWU9024000,65,30 BOXES OF FROZEN PATAGONIAN TOOTHFISH HGT 10...,30383.0,NO MARKS,30383
6,2/6/2020,SUDU59BUE025549X,mark foods,ESTREMAR SA,100 BOXES OF FROZENPATAGONIAN TOOTHFISH HGT 8-...,ARGENTINA,"PORT EVERGLADES,FL",NOT DECLARED,"20,522.00",KG,353,PKG,MMAU1108611,353,100 BOXES OF FROZENPATAGONIAN TOOTHFISH HGT 8-...,30383.0,NO MARKS,30383
7,2/6/2020,SUDU59BUE025341X,mark foods,ESTREMAR SA,26 TOTES OF FROZEN PATAGONIAN TOOTHFISH HGT 15...,ARGENTINA,"PORT EVERGLADES,FL",NOT DECLARED,"23,443.00",KG,36,PKG,MSWU0039009,36,26 TOTES OF FROZEN PATAGONIAN TOOTHFISH HGT 15...,30383.0,NO MARKS,30383
8,2/6/2020,SUDU59BUE025340X,mark foods,ESTREMAR SA,33 TOTES OF FROZEN PATAGONIAN TOOTHFISH HGT 12...,ARGENTINA,"PORT EVERGLADES,FL",NOT DECLARED,"24,348.00",KG,36,PKG,MNBU0346846,36,33 TOTES OF FROZEN PATAGONIAN TOOTHFISH HGT 12...,30383.0,NO MARKS,30383
9,2/6/2020,SUDU59BUE025339X,mark foods,ESTREMAR SA,10 TOTES OF FROZEN PATAGONIAN TOOTHFISH HGT 10...,ARGENTINA,"PORT EVERGLADES,FL",NOT DECLARED,"23,123.00",KG,35,PKG,MMAU1259182,35,10 TOTES OF FROZEN PATAGONIAN TOOTHFISH HGT 10...,30383.0,NO MARKS,30383
10,2/6/2020,SUDU59BUE025338X,mark foods,ESTREMAR SA,16 TOTES OF FROZEN PATAGONIAN TOOTHFISH HGT 8-...,ARGENTINA,"PORT EVERGLADES,FL",NOT DECLARED,"23,911.00",KG,36,PKG,MNBU4129535,36,16 TOTES OF FROZEN PATAGONIAN TOOTHFISH HGT 8-...,30383.0,NO MARKS,30383
11,2/6/2020,SUDU59BUE025337X,mark foods,ESTREMAR SA,450 BOXES OF FROZENPATAGONIAN TOOTHFISH HGT 10...,ARGENTINA,"PORT EVERGLADES,FL",NOT DECLARED,"20,896.00",KG,466,PKG,MNBU3867869,466,450 BOXES OF FROZENPATAGONIAN TOOTHFISH HGT 10...,30383.0,NO MARKS,30383
12,2/6/2020,SUDU59BUE025336X,mark foods,ESTREMAR SA,645 BOXES OF FROZENPATAGONIAN TOOTHFISH HGT 8-...,ARGENTINA,"PORT EVERGLADES,FL",NOT DECLARED,"22,581.00",KG,825,BOX,SUDU8168350,825,645 BOXES OF FROZENPATAGONIAN TOOTHFISH HGT 8-...,30383.0,NO MARKS,30383
13,2/5/2020,SUGBFKPSY196602,mark foods,CFL,PATAGONIAN TOOTHFISH,FALKLAND ISLANDS,"LOS ANGELES,CA",NOT DECLARED,"17,695.00",KG,617,CTN,GESU9590561,617,PATAGONIAN TOOTHFISH,NaN,N/M,30383
14,2/5/2020,SUGBFKPSY196601,mark foods,CFL,PATAGONIAN TOOTHFISH,FALKLAND ISLANDS,"LOS ANGELES,CA",NOT DECLARED,"23,300.00",KG,815,CTN,TEMU9164232,815,PATAGONIAN TOOTHFISH,NaN,M/N,30383
15,2/5/2020,HLCUSCL200103240,OCEAN LEADER S.A. DE C.V.,SOUTH MART SPA,FISH FILLETS 2/2 PART OF CONTAINER 74 TOTAL C...,CHILE,"HOUSTON,TX","HOUSTON,TX","1,922.00",K,74,PCS,HLXU8789860,74,FISH FILLETS 2/2 PART OF CONTAINER 74 TOTAL C...,30485.0,NO MARKS . . . . . .,30485
16,2/5/2020,HLCUSCL200101011,OCEAN LEADER S.A. DE C.V.,PISCISEAFOOD LTDA,FISH FILLETS 1/2 PART OF CONTAINER 375 CARTONS...,CHILE,"HOUSTON,TX","HOUSTON,TX","8,772.00",K,375,PCS,HLXU8789860,375,FISH FILLETS 1/2 PART OF CONTAINER 375 CARTONS...,30485.0,NO MARKS . . . . . . . . . .,30485
17,1/30/2020,SMLU5950827A,TRISTAN INTERNATIONAL,TRANSMARINA CA,BOXES FROZEN FISH SHIPPER PROVIDED HS CODE 03...,ECUADOR,"MIAMI,FL",NOT DECLARED,"39,599.00",L,"2,214.00",BOX,CTWU1601370,"2,214",BOXES FROZEN FISH SHIPPER PROVIDED HS CODE 03...,NaN,NO MARKS NO MARKS NO MARKS NO MARKS NO MARKS N...,030383 030489 030499
18,1/30/2020,SEAUSLN283074,"SLADE GORTON & CO., INC.",PROYECTA CORP S.A.,"419 CARTONS: 12.254,09 KGS. CH ILEAN SEABASS H...",CHILE,"LONG BEACH,CA",NOT DECLARED,"29,343.00",LB,419,CTN,SUDU6183171,419,"419 CARTONS: 12.254,09 KGS. CH ILEAN SEABASS H...",NaN,N/M,30485
19,1/26/2020,MEDUPL102191,NOT DECLARED,NOT DECLARED,FROZEN PATAGONIAN TOOTHFIS H HGT MSC CERTIFIE ...,MAURITIUS,"PORT EVERGLADES,FL",NOT DECLARED,"43,540.00",K,"2,054.00",BAG,BMOU8001480,522,FROZEN PATAGONIAN TOOTHFIS H HGT MSC CERTIFIE ...,NaN,NO MARKS NO MARKS NO MARKS NO MARKS,30383
20,1/25/2020,SUDUB0365A4IQ0U8,"TO THE ORDER OF BANK OF AMERICA,N.A",INVERSIONES PERU PACIFICO S.A.,1405 BOXES WILD PINK PATAGONIANIQF HLSO 16/20 ...,PERU,"BALTIMORE,MD","CHICAGO,IL","16,160.00",KG,"1,405.00",BOX,CXRU1541108,"1,405",1405 BOXES WILD PINK PATAGONIANIQF HLSO 16/20 ...,30617.0,NO MARKS,30617
21,1/24/2020,SUDU59BUE023858X,NOT DECLARED,NOT DECLARED,PATAGONIAN TOOTHFISH(DISSOSTICHUS ELEGINOIDES)...,ARGENTINA,"LONG BEACH,CA",NOT DECLARED,"20,052.00",KG,"1,311.00",CTN,MNBU9088383,"1,311",PATAGONIAN TOOTHFISH(DISSOSTICHUS ELEGINOIDES)...,30383.0,NO MARKS,30383
22,1/24/2020,MEDUPT018058,KENDELL SEAFOOD IMPORTS,SAPMER,FROZEN H & G TAIL OFF PATAGONIAN TOOTHFISH NE ...,FRANCE,"NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY",NOT DECLARED,"23,247.00",K,721,PKG,OTPU6029384,721,FROZEN H & G TAIL OFF PATAGONIAN TOOTHFISH NE ...,NaN,NO MARKS NO MARKS NO MARKS NO MARKS NO MARKS,30383
23,1/23/2020,SUDUB9SCL043399X,KENDELL SEAFOOD,IMP.Y EXP. SAN ISIDRO S.A.,"1 CASE - 49,35 LBS NET WEIGHT FROZEN SEABAS FI...",CHILE,"NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY",NOT DECLARED,"19,282.00",KG,"1,841.00",CAS,MNBU0078487,"1,841","1 CASE - 49,35 LBS NET WEIGHT FROZEN SEABAS FI...",30485.0,NO MARKS,30485
24,1/22/2020,SUDU59MVD008057X,KENDELL SEAFOOD IMPORTS,HONGJIN CORPORATION,NCM 03031100 FROZEN TOOTH FISH HGT WITHOUT COL...,URUGUAY,"NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY",NOT DECLARED,"20,680.00",KG,880,BAG,MNBU4055807,880,NCM 03031100 FROZEN TOOTH FISH HGT WITHOUT COL...,30311.0,NO MARKS,030311 401140
25,1/22/2020,SUDU59MVD008055X,KENDELL SEAFOOD IMPORTS,HONGJIN CORPORATION,NCM 03031100 FROZEN TOOTH FISH HGT WITHOUT COL...,URUGUAY,"NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY",NOT DECLARED,"22,420.00",KG,863,BAG,MNBU0302426,863,NCM 03031100 FROZEN TOOTH FISH HGT WITHOUT COL...,30311.0,NO MARKS,30311
26,1/16/2020,SUDU59BUE025093X,NOT DECLARED,NOT DECLARED,FROZEN TOOTHFISH (DI ELEGINOIDES) NET WEIGHT: ...,ARGENTINA,"PORT EVERGLADES,FL",NOT DECLARED,"18,302.00",KG,563,CTN,SUDU8017755,930,PATAGONIAN TOOTHFISH,NaN,N/M,30383
27,1/14/2020,SUGBFKPSY196600,KENDELL SEAFOOD IMPORTS,CONSOLIDATED FISHERIES LTD,PATAGONIAN TOOTHFISH,FALKLAND ISLANDS,"NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY",NOT DECLARED,"26,916.00",KG,"1,177.00",PKG,CXRU1028672,887,PATAGONIAN TOOTHFISH,NaN,N/M,30383
28,1/14/2020,SUGBFKPSY196598,KENDELL SEAFOOD IMPORTS,CONSOLIDATED FISHERIES LTD,PATAGONIAN TOOTHFISH,FALKLAND ISLANDS,"NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY",NOT DECLARED,"22,887.00",KG,915,PKG,CGMU9395706,53,GRAND WORLD CRUISE ANTARCTICA GUIDE,NaN,$250.00,980000
29,1/12/2020,MEDUCH350448,COLEWILLAIDAN LLC,MARINE FOODS S.A,"300 CASES - 1.530,00 KGS NET WEIGHT CANNED MA ...",CHILE,"NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY",NOT DECLARED,"16,498.00",K,"2,559.00",CTN,MEDU4840497,NaN,NaN,NaN,NaN,NaN
30,1/11/2020,SUDUB9365A4HU96C,"TO THE ORDER OF BANK OF AMERICA,N.A",SEAFROST S.A.C.,01 FCL 1574 CARTONS WILD PINK PATAGONIANIQF QP...,PERU,"BALTIMORE,MD","CHICAGO,IL","18,490.00",KG,"1,574.00",CTN,MNBU3171715,NaN,NaN,NaN,NaN,NaN
31,1/10/2020,SUDU59MVD007435X,KENDELL SEAFOOD IMPORTS,"NH TRADING CO., LTD.",FROZEN TOOTH FISH HGT WITHOUT COLLAR BONE (DI...,URUGUAY,"LONG BEACH,CA",NOT DECLARED,"18,900.00",KG,637,BAG,MNBU9094133,NaN,NaN,NaN,NaN,NaN
32,1/8/2020,SUDU59BUE025094X,NOT DECLARED,ROD INTERNATIONAL,FROZEN TOOTHFISH (DI ELEGINOIDES) NET WEIGHT: ...,ARGENTINA,"NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY",NOT DECLARED,"18,499.00",KG,577,CTN,MNBU3434597,NaN,NaN,NaN,NaN,NaN
33,1/8/2020,HDMUHMLB0609863,"TAI FOONG USA , INC ., 2450 6 TH",CJ CAUTRE FOODS JOINT STOCK COMPA,"SHIPPER'S LOAD, COUNT, STOW & SEAL (5,028 CTNS...",VIETNAM,"LONG BEACH,CA",NOT DECLARED,"19,976.00",KG,"5,028.00",CTN,HDMU5565845,NaN,NaN,NaN,NaN,NaN
34,1/6/2020,SUDUB9SCL040890X,KENDELL SEAFOOD,IMP.Y EXP. SAN ISIDRO S.A.,"337 CASES - 11.523,14 LBS NET WEIGHT FROZEN SE...",CHILE,"PORT EVERGLADES,FL",NOT DECLARED,"20,187.00",KG,"1,205.00",CAS,MNBU4096107,NaN,NaN,NaN,NaN,NaN
35,1/5/2020,SEAUSLN283225,mark foods,sun woo,"FROZEN TOOTHFISH 646 PKGS. WI TH 18.917,53 KG...",CHILE,"LONG BEACH,CA",NOT DECLARED,"42,154.00",LB,646,PKG,MNBU4013226,NaN,NaN,NaN,NaN,NaN
36,1/5/2020,SEAU588085382,mark foods,sun woo,"FROZEN TOOTHFISH 902 PKGS. WITH 19.347,70 K...",CHILE,"LONG BEACH,CA",NOT DECLARED,"43,192.00",LB,902,PKG,MNBU3620020,NaN,NaN,NaN,NaN,NaN
37,1/3/2020,SUGBFKPSY196603,mark foods,CONSOLIDATED FISHERIES LIMITED,PATAGONIAN TOOTHFISH,FALKLAND ISLANDS,"MIAMI,FL",NOT DECLARED,"22,571.00",KG,930,PKG,TCLU1126624,NaN,NaN,NaN,NaN,NaN
38,1/3/2020,SUGBFKPSY196599,mark foods,CONSOLIDATED FISHERIES LIMITED,PATAGONIAN TOOTHFISH,FALKLAND ISLANDS,"MIAMI,FL",NOT DECLARED,"19,613.00",KG,887,PKG,TEMU9420294,NaN,NaN,NaN,NaN,NaN
39,1/3/2020,HAWIZU7020103003,AMSTERDAM,ZUIDERDAM,GRAND WORLD CRUISE ANTARCTICA GUIDE,UNITED STATES,"PORT EVERGLADES,FL",NOT DECLARED,636,KG,53,BOX,NC,NaN,NaN,NaN,NaN,NaN

In [42]:
monthly_data['Date']

0     2/11/2020
1     2/11/2020
2     2/11/2020
3     2/10/2020
4     2/10/2020
5      2/6/2020
6      2/6/2020
7      2/6/2020
8      2/6/2020
9      2/6/2020
10     2/6/2020
11     2/6/2020
12     2/6/2020
13     2/5/2020
14     2/5/2020
15     2/5/2020
16     2/5/2020
17    1/30/2020
18    1/30/2020
19    1/26/2020
20    1/25/2020
21    1/24/2020
22    1/24/2020
23    1/23/2020
24    1/22/2020
25    1/22/2020
26    1/16/2020
27    1/14/2020
28    1/14/2020
29    1/12/2020
30    1/11/2020
31    1/10/2020
32     1/8/2020
33     1/8/2020
34     1/6/2020
35     1/5/2020
36     1/5/2020
37     1/3/2020
38     1/3/2020
39     1/3/2020
Name: Date, dtype: object

In [43]:
monthly_data_df = pd.DataFrame(monthly_data)
monthly_data_df

,Date,Bill of lading Nbr.,Consignee Declared,Shipper Declared,Short Container Description,Country of Origin,Port of Arrival,Final Destination,Weight,Weight Unit,Quantity,Quantity Unit,Container,Pieces,Description,Harmonized,Marks & Numbers,HS
0,2/11/2020,SUDU59BUE026704X,STAVIS SEAFOOD LLC,EMPRESA PESQUERA DE LA PATAGONIA Y,281-BAGS-FROZEN PATAGONIAN TOOTHFISH HGT IWP 0...,ARGENTINA,"NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY",NOT DECLARED,"20,609.00",KG,842,BAG,MNBU3923073,842,281-BAGS-FROZEN PATAGONIAN TOOTHFISH HGT IWP 0...,30383.0,PESANTAR,30383
1,2/11/2020,SUDU59BUE026679X,STAVIS SEAFOOD LLC,EMPRESA PESQUERA DE LA PATAGONIA Y,285-BAGS-FROZEN PATAGONIAN TOOTHFISH HGT IWP 0...,ARGENTINA,"NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY",NOT DECLARED,"21,540.00",KG,870,BAG,SUDU6076487,870,285-BAGS-FROZEN PATAGONIAN TOOTHFISH HGT IWP 0...,30383.0,PESANTAR,30383
2,2/11/2020,SUDU59BUE026512X,mark foods,PESANTAR,139-BAGS-FROZEN PATAGONIAN TOOTHFISH HGT IWP 0...,ARGENTINA,"NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY",NOT DECLARED,"22,352.00",KG,998,BAG,MWCU6910169,998,139-BAGS-FROZEN PATAGONIAN TOOTHFISH HGT IWP 0...,30383.0,PESANTAR,30383
3,2/10/2020,MEDUCH355884,SABANAMAR INTERNATIONAL L.L.C.,ISAM CHILE S.A.,"146 CARTONSFROZEN CHILEAN SEABASS HGT IWP, VA ...",CHILE,"NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY",NOT DECLARED,"18,648.00",K,"1,576.00",CTN,TRIU8926367,"1,576","146 CARTONSFROZEN CHILEAN SEABASS HGT IWP, VA ...",NaN,NO MARKS NO MARKS NO MARKS NO MARKS NO MARKS,30481
4,2/10/2020,SUDUB0SCL000225X,DEEP BLUE FISHERY LLC,PROYECTA CORP S.A.,"238CARTONS: 4.544,15KGS. NET WEIGHT CHILEAN SE...",CHILE,"PORT EVERGLADES,FL",NOT DECLARED,"5,100.00",KG,238,CTN,MNBU3295850,238,"238CARTONS: 4.544,15KGS. NET WEIGHT CHILEAN SE...",30485.0,NO MARKS,30485
5,2/6/2020,SUDU59BUE025610X,mark foods,ESTREMAR SA,30 BOXES OF FROZEN PATAGONIAN TOOTHFISH HGT 10...,ARGENTINA,"PORT EVERGLADES,FL",NOT DECLARED,"22,809.00",KG,65,PKG,MSWU9024000,65,30 BOXES OF FROZEN PATAGONIAN TOOTHFISH HGT 10...,30383.0,NO MARKS,30383
6,2/6/2020,SUDU59BUE025549X,mark foods,ESTREMAR SA,100 BOXES OF FROZENPATAGONIAN TOOTHFISH HGT 8-...,ARGENTINA,"PORT EVERGLADES,FL",NOT DECLARED,"20,522.00",KG,353,PKG,MMAU1108611,353,100 BOXES OF FROZENPATAGONIAN TOOTHFISH HGT 8-...,30383.0,NO MARKS,30383
7,2/6/2020,SUDU59BUE025341X,mark foods,ESTREMAR SA,26 TOTES OF FROZEN PATAGONIAN TOOTHFISH HGT 15...,ARGENTINA,"PORT EVERGLADES,FL",NOT DECLARED,"23,443.00",KG,36,PKG,MSWU0039009,36,26 TOTES OF FROZEN PATAGONIAN TOOTHFISH HGT 15...,30383.0,NO MARKS,30383
8,2/6/2020,SUDU59BUE025340X,mark foods,ESTREMAR SA,33 TOTES OF FROZEN PATAGONIAN TOOTHFISH HGT 12...,ARGENTINA,"PORT EVERGLADES,FL",NOT DECLARED,"24,348.00",KG,36,PKG,MNBU0346846,36,33 TOTES OF FROZEN PATAGONIAN TOOTHFISH HGT 12...,30383.0,NO MARKS,30383
9,2/6/2020,SUDU59BUE025339X,mark foods,ESTREMAR SA,10 TOTES OF FROZEN PATAGONIAN TOOTHFISH HGT 10...,ARGENTINA,"PORT EVERGLADES,FL",NOT DECLARED,"23,123.00",KG,35,PKG,MMAU1259182,35,10 TOTES OF FROZEN PATAGONIAN TOOTHFISH HGT 10...,30383.0,NO MARKS,30383
10,2/6/2020,SUDU59BUE025338X,mark foods,ESTREMAR SA,16 TOTES OF FROZEN PATAGONIAN TOOTHFISH HGT 8-...,ARGENTINA,"PORT EVERGLADES,FL",NOT DECLARED,"23,911.00",KG,36,PKG,MNBU4129535,36,16 TOTES OF FROZEN PATAGONIAN TOOTHFISH HGT 8-...,30383.0,NO MARKS,30383
11,2/6/2020,SUDU59BUE025337X,mark foods,ESTREMAR SA,450 BOXES OF FROZENPATAGONIAN TOOTHFISH HGT 10...,ARGENTINA,"PORT EVERGLADES,FL",NOT DECLARED,"20,896.00",KG,466,PKG,MNBU3867869,466,450 BOXES OF FROZENPATAGONIAN TOOTHFISH HGT 10...,30383.0,NO MARKS,30383
12,2/6/2020,SUDU59BUE025336X,mark foods,ESTREMAR SA,645 BOXES OF FROZENPATAGONIAN TOOTHFISH HGT 8-...,ARGENTINA,"PORT EVERGLADES,FL",NOT DECLARED,"22,581.00",KG,825,BOX,SUDU8168350,825,645 BOXES OF FROZENPATAGONIAN TOOTHFISH HGT 8-...,30383.0,NO MARKS,30383
13,2/5/2020,SUGBFKPSY196602,mark foods,CFL,PATAGONIAN TOOTHFISH,FALKLAND ISLANDS,"LOS ANGELES,CA",NOT DECLARED,"17,695.00",KG,617,CTN,GESU9590561,617,PATAGONIAN TOOTHFISH,NaN,N/M,30383
14,2/5/2020,SUGBFKPSY196601,mark foods,CFL,PATAGONIAN TOOTHFISH,FALKLAND ISLANDS,"LOS ANGELES,CA",NOT DECLARED,"23,300.00",KG,815,CTN,TEMU9164232,815,PATAGONIAN TOOTHFISH,NaN,M/N,30383
15,2/5/2020,HLCUSCL200103240,OCEAN LEADER S.A. DE C.V.,SOUTH MART SPA,FISH FILLETS 2/2 PART OF CONTAINER 74 TOTAL C...,CHILE,"HOUSTON,TX","HOUSTON,TX","1,922.00",K,74,PCS,HLXU8789860,74,FISH FILLETS 2/2 PART OF CONTAINER 74 TOTAL C...,30485.0,NO MARKS . . . . . .,30485
16,2/5/2020,HLCUSCL200101011,OCEAN LEADER S.A. DE C.V.,PISCISEAFOOD LTDA,FISH FILLETS 1/2 PART OF CONTAINER 375 CARTONS...,CHILE,"HOUSTON,TX","HOUSTON,TX","8,772.00",K,375,PCS,HLXU8789860,375,FISH FILLETS 1/2 PART OF CONTAINER 375 CARTONS...,30485.0,NO MARKS . . . . . . . . . .,30485
17,1/30/2020,SMLU5950827A,TRISTAN INTERNATIONAL,TRANSMARINA CA,BOXES FROZEN FISH SHIPPER PROVIDED HS CODE 03...,ECUADOR,"MIAMI,FL",NOT DECLARED,"39,599.00",L,"2,214.00",BOX,CTWU1601370,"2,214",BOXES FROZEN FISH SHIPPER PROVIDED HS CODE 03...,NaN,NO MARKS NO MARKS NO MARKS NO MARKS NO MARKS N...,030383 030489 030499
18,1/30/2020,SEAUSLN283074,"SLADE GORTON & CO., INC.",PROYECTA CORP S.A.,"419 CARTONS: 12.254,09 KGS. CH ILEAN SEABASS H...",CHILE,"LONG BEACH,CA",NOT DECLARED,"29,343.00",LB,419,CTN,SUDU6183171,419,"419 CARTONS: 12.254,09 KGS. CH ILEAN SEABASS H...",NaN,N/M,30485
19,1/26/2020,MEDUPL102191,NOT DECLARED,NOT DECLARED,FROZEN PATAGONIAN TOOTHFIS H HGT MSC CERTIFIE ...,MAURITIUS,"PORT EVERGLADES,FL",NOT DECLARED,"43,540.00",K,"2,054.00",BAG,BMOU8001480,522,FROZEN PATAGONIAN TOOTHFIS H HGT MSC CERTIFIE ...,NaN,NO MARKS NO MARKS NO MARKS NO MARKS,30383
20,1/25/2020,SUDUB0365A4IQ0U8,"TO THE ORDER OF BANK OF AMERICA,N.A",INVERSIONES PERU PACIFICO S.A.,1405 BOXES WILD PINK PATAGONIANIQF HLSO 16/20 ...,PERU,"BALTIMORE,MD","CHICAGO,IL","16,160.00",KG,"1,405.00",BOX,CXRU1541108,"1,405",1405 BOXES WILD PINK PATAGONIANIQF HLSO 16/20 ...,30617.0,NO MARKS,30617
21,1/24/2020,SUDU59BUE023858X,NOT DECLARED,NOT DECLARED,PATAGONIAN TOOTHFISH(DISSOSTICHUS ELEGINOIDES)...,ARGENTINA,"LONG BEACH,CA",NOT DECLARED,"20,052.00",KG,"1,311.00",CTN,MNBU9088383,"1,311",PATAGONIAN TOOTHFISH(DISSOSTICHUS ELEGINOIDES)...,30383.0,NO MARKS,30383
22,1/24/2020,MEDUPT018058,KENDELL SEAFOOD IMPORTS,SAPMER,FROZEN H & G TAIL OFF PATAGONIAN TOOTHFISH NE ...,FRANCE,"NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY",NOT DECLARED,"23,247.00",K,721,PKG,OTPU6029384,721,FROZEN H & G TAIL OFF PATAGONIAN TOOTHFISH NE ...,NaN,NO MARKS NO MARKS NO MARKS NO MARKS NO MARKS,30383
23,1/23/2020,SUDUB9SCL043399X,KENDELL SEAFOOD,IMP.Y EXP. SAN ISIDRO S.A.,"1 CASE - 49,35 LBS NET WEIGHT FROZEN SEABAS FI...",CHILE,"NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY",NOT DECLARED,"19,282.00",KG,"1,841.00",CAS,MNBU0078487,"1,841","1 CASE - 49,35 LBS NET WEIGHT FROZEN SEABAS FI...",30485.0,NO MARKS,30485
24,1/22/2020,SUDU59MVD008057X,KENDELL SEAFOOD IMPORTS,HONGJIN CORPORATION,NCM 03031100 FROZEN TOOTH FISH HGT WITHOUT COL...,URUGUAY,"NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY",NOT DECLARED,"20,680.00",KG,880,BAG,MNBU4055807,880,NCM 03031100 FROZEN TOOTH FISH HGT WITHOUT COL...,30311.0,NO MARKS,030311 401140
25,1/22/2020,SUDU59MVD008055X,KENDELL SEAFOOD IMPORTS,HONGJIN CORPORATION,NCM 03031100 FROZEN TOOTH FISH HGT WITHOUT COL...,URUGUAY,"NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY",NOT DECLARED,"22,420.00",KG,863,BAG,MNBU0302426,863,NCM 03031100 FROZEN TOOTH FISH HGT WITHOUT COL...,30311.0,NO MARKS,30311
26,1/16/2020,SUDU59BUE025093X,NOT DECLARED,NOT DECLARED,FROZEN TOOTHFISH (DI ELEGINOIDES) NET WEIGHT: ...,ARGENTINA,"PORT EVERGLADES,FL",NOT DECLARED,"18,302.00",KG,563,CTN,SUDU8017755,930,PATAGONIAN TOOTHFISH,NaN,N/M,30383
27,1/14/2020,SUGBFKPSY196600,KENDELL SEAFOOD IMPORTS,CONSOLIDATED FISHERIES LTD,PATAGONIAN TOOTHFISH,FALKLAND ISLANDS,"NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY",NOT DECLARED,"26,916.00",KG,"1,177.00",PKG,CXRU1028672,887,PATAGONIAN TOOTHFISH,NaN,N/M,30383
28,1/14/2020,SUGBFKPSY196598,KENDELL SEAFOOD IMPORTS,CONSOLIDATED FISHERIES LTD,PATAGONIAN TOOTHFISH,FALKLAND ISLANDS,"NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY",NOT DECLARED,"22,887.00",KG,915,PKG,CGMU9395706,53,GRAND WORLD CRUISE ANTARCTICA GUIDE,NaN,$250.00,980000
29,1/12/2020,MEDUCH350448,COLEWILLAIDAN LLC,MARINE FOODS S.A,"300 CASES - 1.530,00 KGS NET WEIGHT CANNED MA ...",CHILE,"NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY",NOT DECLARED,"16,498.00",K,"2,559.00",CTN,MEDU4840497,NaN,NaN,NaN,NaN,NaN
30,1/11/2020,SUDUB9365A4HU96C,"TO THE ORDER OF BANK OF AMERICA,N.A",SEAFROST S.A.C.,01 FCL 1574 CARTONS WILD PINK PATAGONIANIQF QP...,PERU,"BALTIMORE,MD","CHICAGO,IL","18,490.00",KG,"1,574.00",CTN,MNBU3171715,NaN,NaN,NaN,NaN,NaN
31,1/10/2020,SUDU59MVD007435X,KENDELL SEAFOOD IMPORTS,"NH TRADING CO., LTD.",FROZEN TOOTH FISH HGT WITHOUT COLLAR BONE (DI...,URUGUAY,"LONG BEACH,CA",NOT DECLARED,"18,900.00",KG,637,BAG,MNBU9094133,NaN,NaN,NaN,NaN,NaN
32,1/8/2020,SUDU59BUE025094X,NOT DECLARED,ROD INTERNATIONAL,FROZEN TOOTHFISH (DI ELEGINOIDES) NET WEIGHT: ...,ARGENTINA,"NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY",NOT DECLARED,"18,499.00",KG,577,CTN,MNBU3434597,NaN,NaN,NaN,NaN,NaN
33,1/8/2020,HDMUHMLB0609863,"TAI FOONG USA , INC ., 2450 6 TH",CJ CAUTRE FOODS JOINT STOCK COMPA,"SHIPPER'S LOAD, COUNT, STOW & SEAL (5,028 CTNS...",VIETNAM,"LONG BEACH,CA",NOT DECLARED,"19,976.00",KG,"5,028.00",CTN,HDMU5565845,NaN,NaN,NaN,NaN,NaN
34,1/6/2020,SUDUB9SCL040890X,KENDELL SEAFOOD,IMP.Y EXP. SAN ISIDRO S.A.,"337 CASES - 11.523,14 LBS NET WEIGHT FROZEN SE...",CHILE,"PORT EVERGLADES,FL",NOT DECLARED,"20,187.00",KG,"1,205.00",CAS,MNBU4096107,NaN,NaN,NaN,NaN,NaN
35,1/5/2020,SEAUSLN283225,mark foods,sun woo,"FROZEN TOOTHFISH 646 PKGS. WI TH 18.917,53 KG...",CHILE,"LONG BEACH,CA",NOT DECLARED,"42,154.00",LB,646,PKG,MNBU4013226,NaN,NaN,NaN,NaN,NaN
36,1/5/2020,SEAU588085382,mark foods,sun woo,"FROZEN TOOTHFISH 902 PKGS. WITH 19.347,70 K...",CHILE,"LONG BEACH,CA",NOT DECLARED,"43,192.00",LB,902,PKG,MNBU3620020,NaN,NaN,NaN,NaN,NaN
37,1/3/2020,SUGBFKPSY196603,mark foods,CONSOLIDATED FISHERIES LIMITED,PATAGONIAN TOOTHFISH,FALKLAND ISLANDS,"MIAMI,FL",NOT DECLARED,"22,571.00",KG,930,PKG,TCLU1126624,NaN,NaN,NaN,NaN,NaN
38,1/3/2020,SUGBFKPSY196599,mark foods,CONSOLIDATED FISHERIES LIMITED,PATAGONIAN TOOTHFISH,FALKLAND ISLANDS,"MIAMI,FL",NOT DECLARED,"19,613.00",KG,887,PKG,TEMU9420294,NaN,NaN,NaN,NaN,NaN
39,1/3/2020,HAWIZU7020103003,AMSTERDAM,ZUIDERDAM,GRAND WORLD CRUISE ANTARCTICA GUIDE,UNITED STATES,"PORT EVERGLADES,FL",NOT DECLARED,636,KG,53,BOX,NC,NaN,NaN,NaN,NaN,NaN

In [8]:
monthly_data_df["Date"].value_counts().reset_index()

        index  Date
0    2/6/2020     8
1    2/5/2020     4
2    1/3/2020     3
3   2/11/2020     3
4   1/14/2020     2
5    1/8/2020     2
6   1/24/2020     2
7   2/10/2020     2
8   1/30/2020     2
9    1/5/2020     2
10  1/22/2020     2
11  1/25/2020     1
12  1/16/2020     1
13  1/12/2020     1
14   1/6/2020     1
15  1/10/2020     1
16  1/11/2020     1
17  1/26/2020     1
18  1/23/2020     1

In [44]:
for col in monthly_data_df.columns: 
    print(col)

Date
Bill of lading Nbr.
Consignee Declared
Shipper Declared
Short Container Description
Country of Origin
Port of Arrival
Final Destination
Weight
Weight Unit
Quantity
Quantity Unit
Container
Pieces
Description
Harmonized
Marks & Numbers
HS

In [46]:
date = pd.date_range('1/1/2020', '1/31/2020')
date

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12',
               '2020-01-13', '2020-01-14', '2020-01-15', '2020-01-16',
               '2020-01-17', '2020-01-18', '2020-01-19', '2020-01-20',
               '2020-01-21', '2020-01-22', '2020-01-23', '2020-01-24',
               '2020-01-25', '2020-01-26', '2020-01-27', '2020-01-28',
               '2020-01-29', '2020-01-30', '2020-01-31'],
              dtype='datetime64[ns]', freq='D')

In [49]:
columns

['Date', 'Shipper Declared', 'Country of Origin', 'Weight', 'Port of Arrival']

In [66]:
monthly_data_df['datetime'] = pd.to_datetime(monthly_data_df['Date'])
monthly_data_df['datetime']

0    2020-02-11
1    2020-02-11
2    2020-02-11
3    2020-02-10
4    2020-02-10
5    2020-02-06
6    2020-02-06
7    2020-02-06
8    2020-02-06
9    2020-02-06
10   2020-02-06
11   2020-02-06
12   2020-02-06
13   2020-02-05
14   2020-02-05
15   2020-02-05
16   2020-02-05
17   2020-01-30
18   2020-01-30
19   2020-01-26
20   2020-01-25
21   2020-01-24
22   2020-01-24
23   2020-01-23
24   2020-01-22
25   2020-01-22
26   2020-01-16
27   2020-01-14
28   2020-01-14
29   2020-01-12
30   2020-01-11
31   2020-01-10
32   2020-01-08
33   2020-01-08
34   2020-01-06
35   2020-01-05
36   2020-01-05
37   2020-01-03
38   2020-01-03
39   2020-01-03
Name: datetime, dtype: datetime64[ns]

In [71]:
date = pd.date_range('2020-01-01', '2020-01-31')
date

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12',
               '2020-01-13', '2020-01-14', '2020-01-15', '2020-01-16',
               '2020-01-17', '2020-01-18', '2020-01-19', '2020-01-20',
               '2020-01-21', '2020-01-22', '2020-01-23', '2020-01-24',
               '2020-01-25', '2020-01-26', '2020-01-27', '2020-01-28',
               '2020-01-29', '2020-01-30', '2020-01-31'],
              dtype='datetime64[ns]', freq='D')

In [72]:
columns = ["Date", "Shipper Declared", "Country of Origin", "Weight", "Port of Arrival", "datetime"]
columns

['Date',
 'Shipper Declared',
 'Country of Origin',
 'Weight',
 'Port of Arrival',
 'datetime']

In [75]:
monthly_data_df, columns

(         Date Bill of lading Nbr.                   Consignee Declared  \
 0   2/11/2020    SUDU59BUE026704X                   STAVIS SEAFOOD LLC
 1   2/11/2020    SUDU59BUE026679X                   STAVIS SEAFOOD LLC
 2   2/11/2020    SUDU59BUE026512X                           mark foods
 3   2/10/2020        MEDUCH355884       SABANAMAR INTERNATIONAL L.L.C.
 4   2/10/2020    SUDUB0SCL000225X                DEEP BLUE FISHERY LLC
 5    2/6/2020    SUDU59BUE025610X                           mark foods
 6    2/6/2020    SUDU59BUE025549X                           mark foods
 7    2/6/2020    SUDU59BUE025341X                           mark foods
 8    2/6/2020    SUDU59BUE025340X                           mark foods
 9    2/6/2020    SUDU59BUE025339X                           mark foods
 10   2/6/2020    SUDU59BUE025338X                           mark foods
 11   2/6/2020    SUDU59BUE025337X                           mark foods
 12   2/6/2020    SUDU59BUE025336X                           mark foods
 13   2/5/2020     SUGBFKPSY196602                           mark foods
 14   2/5/2020     SUGBFKPSY196601                           mark foods
 15   2/5/2020    HLCUSCL200103240            OCEAN LEADER S.A. DE C.V.
 16   2/5/2020    HLCUSCL200101011            OCEAN LEADER S.A. DE C.V.
 17  1/30/2020        SMLU5950827A                TRISTAN INTERNATIONAL
 18  1/30/2020       SEAUSLN283074             SLADE GORTON & CO., INC.
 19  1/26/2020        MEDUPL102191                         NOT DECLARED
 20  1/25/2020    SUDUB0365A4IQ0U8  TO THE ORDER OF BANK OF AMERICA,N.A
 21  1/24/2020    SUDU59BUE023858X                         NOT DECLARED
 22  1/24/2020        MEDUPT018058              KENDELL SEAFOOD IMPORTS
 23  1/23/2020    SUDUB9SCL043399X                      KENDELL SEAFOOD
 24  1/22/2020    SUDU59MVD008057X              KENDELL SEAFOOD IMPORTS
 25  1/22/2020    SUDU59MVD008055X              KENDELL SEAFOOD IMPORTS
 26  1/16/2020    SUDU59BUE025093X                         NOT DECLARED
 27  1/14/2020     SUGBFKPSY196600              KENDELL SEAFOOD IMPORTS
 28  1/14/2020     SUGBFKPSY196598              KENDELL SEAFOOD IMPORTS
 29  1/12/2020        MEDUCH350448                    COLEWILLAIDAN LLC
 30  1/11/2020    SUDUB9365A4HU96C  TO THE ORDER OF BANK OF AMERICA,N.A
 31  1/10/2020    SUDU59MVD007435X              KENDELL SEAFOOD IMPORTS
 32   1/8/2020    SUDU59BUE025094X                         NOT DECLARED
 33   1/8/2020     HDMUHMLB0609863     TAI FOONG USA , INC ., 2450 6 TH
 34   1/6/2020    SUDUB9SCL040890X                      KENDELL SEAFOOD
 35   1/5/2020       SEAUSLN283225                           mark foods
 36   1/5/2020       SEAU588085382                           mark foods
 37   1/3/2020     SUGBFKPSY196603                           mark foods
 38   1/3/2020     SUGBFKPSY196599                           mark foods
 39   1/3/2020    HAWIZU7020103003                            AMSTERDAM

                       Shipper Declared  \
 0   EMPRESA PESQUERA DE LA PATAGONIA Y
 1   EMPRESA PESQUERA DE LA PATAGONIA Y
 2                             PESANTAR
 3                      ISAM CHILE S.A.
 4                   PROYECTA CORP S.A.
 5                          ESTREMAR SA
 6                          ESTREMAR SA
 7                          ESTREMAR SA
 8                          ESTREMAR SA
 9                          ESTREMAR SA
 10                         ESTREMAR SA
 11                         ESTREMAR SA
 12                         ESTREMAR SA
 13                                 CFL
 14                                 CFL
 15                      SOUTH MART SPA
 16                   PISCISEAFOOD LTDA
 17                      TRANSMARINA CA
 18                  PROYECTA CORP S.A.
 19                        NOT DECLARED
 20      INVERSIONES PERU PACIFICO S.A.
 21                        NOT DECLARED
 22                              SAPMER
 23          IMP.Y EXP. SAN ISIDRO S.A.
 24                 HONGJIN CORPORATION
 25                 HONGJIN CORPORATION
 26                        NOT DECLARED
 27          CONSOLIDATED FISHERIES LTD
 28          CONSOLIDATED FISHERIES LTD
 29                    MARINE FOODS S.A
 30                     SEAFROST S.A.C.
 31                NH TRADING CO., LTD.
 32                  ROD INTERNATIONAL
 33   CJ CAUTRE FOODS JOINT STOCK COMPA
 34          IMP.Y EXP. SAN ISIDRO S.A.
 35                             sun woo
 36                             sun woo
 37      CONSOLIDATED FISHERIES LIMITED
 38      CONSOLIDATED FISHERIES LIMITED
 39                           ZUIDERDAM

                           Short Container Description Country of Origin  \
 0   281-BAGS-FROZEN PATAGONIAN TOOTHFISH HGT IWP 0...         ARGENTINA
 1   285-BAGS-FROZEN PATAGONIAN TOOTHFISH HGT IWP 0...         ARGENTINA
 2   139-BAGS-FROZEN PATAGONIAN TOOTHFISH HGT IWP 0...         ARGENTINA
 3   146 CARTONSFROZEN CHILEAN SEABASS HGT IWP, VA ...             CHILE
 4   238CARTONS: 4.544,15KGS. NET WEIGHT CHILEAN SE...             CHILE
 5   30 BOXES OF FROZEN PATAGONIAN TOOTHFISH HGT 10...         ARGENTINA
 6   100 BOXES OF FROZENPATAGONIAN TOOTHFISH HGT 8-...         ARGENTINA
 7   26 TOTES OF FROZEN PATAGONIAN TOOTHFISH HGT 15...         ARGENTINA
 8   33 TOTES OF FROZEN PATAGONIAN TOOTHFISH HGT 12...         ARGENTINA
 9   10 TOTES OF FROZEN PATAGONIAN TOOTHFISH HGT 10...         ARGENTINA
 10  16 TOTES OF FROZEN PATAGONIAN TOOTHFISH HGT 8-...         ARGENTINA
 11  450 BOXES OF FROZENPATAGONIAN TOOTHFISH HGT 10...         ARGENTINA
 12  645 BOXES OF FROZENPATAGONIAN TOOTHFISH HGT 8-...         ARGENTINA
 13                               PATAGONIAN TOOTHFISH  FALKLAND ISLANDS
 14                               PATAGONIAN TOOTHFISH  FALKLAND ISLANDS
 15  FISH FILLETS 2/2 PART OF CONTAINER 74  TOTAL C...             CHILE
 16  FISH FILLETS 1/2 PART OF CONTAINER 375 CARTONS...             CHILE
 17  BOXES FROZEN FISH SHIPPER PROVIDED HS CODE  03...           ECUADOR
 18  419 CARTONS: 12.254,09 KGS. CH ILEAN SEABASS H...             CHILE
 19  FROZEN PATAGONIAN TOOTHFIS H HGT MSC CERTIFIE ...         MAURITIUS
 20  1405 BOXES WILD PINK PATAGONIANIQF HLSO 16/20 ...              PERU
 21  PATAGONIAN TOOTHFISH(DISSOSTICHUS ELEGINOIDES)...         ARGENTINA
 22  FROZEN H & G TAIL OFF PATAGONIAN TOOTHFISH NE ...            FRANCE
 23  1 CASE - 49,35 LBS NET WEIGHT FROZEN SEABAS FI...             CHILE
 24  NCM 03031100 FROZEN TOOTH FISH HGT WITHOUT COL...           URUGUAY
 25  NCM 03031100 FROZEN TOOTH FISH HGT WITHOUT COL...           URUGUAY
 26  FROZEN TOOTHFISH (DI ELEGINOIDES) NET WEIGHT: ...         ARGENTINA
 27                               PATAGONIAN TOOTHFISH  FALKLAND ISLANDS
 28                               PATAGONIAN TOOTHFISH  FALKLAND ISLANDS
 29  300 CASES - 1.530,00 KGS NET WEIGHT CANNED MA ...             CHILE
 30  01 FCL 1574 CARTONS WILD PINK PATAGONIANIQF QP...              PERU
 31  FROZEN  TOOTH FISH HGT WITHOUT COLLAR BONE (DI...           URUGUAY
 32  FROZEN TOOTHFISH (DI ELEGINOIDES) NET WEIGHT: ...         ARGENTINA
 33  SHIPPER'S LOAD, COUNT, STOW & SEAL (5,028 CTNS...           VIETNAM
 34  337 CASES - 11.523,14 LBS NET WEIGHT FROZEN SE...             CHILE
 35  FROZEN TOOTHFISH  646 PKGS. WI TH 18.917,53 KG...             CHILE
 36  FROZEN TOOTHFISH    902 PKGS. WITH 19.347,70 K...             CHILE
 37                               PATAGONIAN TOOTHFISH  FALKLAND ISLANDS
 38                               PATAGONIAN TOOTHFISH  FALKLAND ISLANDS
 39                GRAND WORLD CRUISE ANTARCTICA GUIDE     UNITED STATES

                              Port of Arrival Final Destination     Weight  \
 0   NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY      NOT DECLARED  20,609.00
 1   NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY      NOT DECLARED  21,540.00
 2   NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY      NOT DECLARED  22,352.00
 3   NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY      NOT DECLARED  18,648.00
 4                         PORT EVERGLADES,FL      NOT DECLARED   5,100.00
 5                         PORT EVERGLADES,FL      NOT DECLARED  22,809.00
 6                         PORT EVERGLADES,FL      NOT DECLARED  20,522.00
 7                         PORT EVERGLADES,FL      NOT DECLARED  23,443.00
 8                         PORT EVERGLADES,FL      NOT DECLARED  24,348.00
 9                         PORT EVERGLADES,FL      NOT DECLARED  23,123.00
 10                        PORT EVERGLADES,FL      NOT DECLARED  23,911.00
 11                        PORT EVERGLADES,FL      NOT DECLARED  20,896.00
 12                        PORT EVERGLADES,FL      NOT DECLARED  22,581.00
 13                            LOS ANGELES,CA      NOT DECLARED  17,695.00
 14                            LOS ANGELES,CA      NOT DECLARED  23,300.00
 15                                HOUSTON,TX        HOUSTON,TX   1,922.00
 16                                HOUSTON,TX        HOUSTON,TX   8,772.00
 17                                  MIAMI,FL      NOT DECLARED  39,599.00
 18                             LONG BEACH,CA      NOT DECLARED  29,343.00
 19                        PORT EVERGLADES,FL      NOT DECLARED  43,540.00
 20                              BALTIMORE,MD        CHICAGO,IL  16,160.00
 21                             LONG BEACH,CA      NOT DECLARED  20,052.00
 22  NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY      NOT DECLARED  23,247.00
 23  NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY      NOT DECLARED  19,282.00
 24  NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY      NOT DECLARED  20,680.00
 25  NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY      NOT DECLARED  22,420.00
 26                        PORT EVERGLADES,FL      NOT DECLARED  18,302.00
 27  NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY      NOT DECLARED  26,916.00
 28  NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY      NOT DECLARED  22,887.00
 29  NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY      NOT DECLARED  16,498.00
 30                              BALTIMORE,MD        CHICAGO,IL  18,490.00
 31                             LONG BEACH,CA      NOT DECLARED  18,900.00
 32  NEW YORK/NEWARK AREA, NEWARK, NEW JERSEY      NOT DECLARED  18,499.00
 33                             LONG BEACH,CA      NOT DECLARED  19,976.00
 34                        PORT EVERGLADES,FL      NOT DECLARED  20,187.00
 35                             LONG BEACH,CA      NOT DECLARED  42,154.00
 36                             LONG BEACH,CA      NOT DECLARED  43,192.00
 37                                  MIAMI,FL      NOT DECLARED  22,571.00
 38                                  MIAMI,FL      NOT DECLARED  19,613.00
 39                        PORT EVERGLADES,FL      NOT DECLARED        636

    Weight Unit  Quantity Quantity Unit    Container Pieces  \
 0           KG       842           BAG  MNBU3923073    842
 1           KG       870           BAG  SUDU6076487    870
 2           KG       998           BAG  MWCU6910169    998
 3            K  1,576.00           CTN  TRIU8926367  1,576
 4           KG       238           CTN  MNBU3295850    238
 5           KG        65           PKG  MSWU9024000     65
 6           KG       353           PKG  MMAU1108611    353
 7           KG        36           PKG  MSWU0039009     36
 8           KG        36           PKG  MNBU0346846     36
 9           KG        35           PKG  MMAU1259182     35
 10          KG        36           PKG  MNBU4129535     36
 11          KG       466           PKG  MNBU3867869    466
 12          KG       825           BOX  SUDU8168350    825
 13          KG       617           CTN  GESU9590561    617
 14          KG       815           CTN  TEMU9164232    815
 15           K        74           PCS  HLXU8789860     74
 16           K       375           PCS  HLXU8789860    375
 17           L  2,214.00           BOX  CTWU1601370  2,214
 18          LB       419           CTN  SUDU6183171    419
 19           K  2,054.00           BAG  BMOU8001480    522
 20          KG  1,405.00           BOX  CXRU1541108  1,405
 21          KG  1,311.00           CTN  MNBU9088383  1,311
 22           K       721           PKG  OTPU6029384    721
 23          KG  1,841.00           CAS  MNBU0078487  1,841
 24          KG       880           BAG  MNBU4055807    880
 25          KG       863           BAG  MNBU0302426    863
 26          KG       563           CTN  SUDU8017755    930
 27          KG  1,177.00           PKG  CXRU1028672    887
 28          KG       915           PKG  CGMU9395706     53
 29           K  2,559.00           CTN  MEDU4840497    NaN
 30          KG  1,574.00           CTN  MNBU3171715    NaN
 31          KG       637           BAG  MNBU9094133    NaN
 32          KG       577           CTN  MNBU3434597    NaN
 33          KG  5,028.00           CTN  HDMU5565845    NaN
 34          KG  1,205.00           CAS  MNBU4096107    NaN
 35          LB       646           PKG  MNBU4013226    NaN
 36          LB       902           PKG  MNBU3620020    NaN
 37          KG       930           PKG  TCLU1126624    NaN
 38          KG       887           PKG  TEMU9420294    NaN
 39          KG        53           BOX           NC    NaN

                                           Description  Harmonized  \
 0   281-BAGS-FROZEN PATAGONIAN TOOTHFISH HGT IWP 0...     30383.0
 1   285-BAGS-FROZEN PATAGONIAN TOOTHFISH HGT IWP 0...     30383.0
 2   139-BAGS-FROZEN PATAGONIAN TOOTHFISH HGT IWP 0...     30383.0
 3   146 CARTONSFROZEN CHILEAN SEABASS HGT IWP, VA ...         NaN
 4   238CARTONS: 4.544,15KGS. NET WEIGHT CHILEAN SE...     30485.0
 5   30 BOXES OF FROZEN PATAGONIAN TOOTHFISH HGT 10...     30383.0
 6   100 BOXES OF FROZENPATAGONIAN TOOTHFISH HGT 8-...     30383.0
 7   26 TOTES OF FROZEN PATAGONIAN TOOTHFISH HGT 15...     30383.0
 8   33 TOTES OF FROZEN PATAGONIAN TOOTHFISH HGT 12...     30383.0
 9   10 TOTES OF FROZEN PATAGONIAN TOOTHFISH HGT 10...     30383.0
 10  16 TOTES OF FROZEN PATAGONIAN TOOTHFISH HGT 8-...     30383.0
 11  450 BOXES OF FROZENPATAGONIAN TOOTHFISH HGT 10...     30383.0
 12  645 BOXES OF FROZENPATAGONIAN TOOTHFISH HGT 8-...     30383.0
 13                               PATAGONIAN TOOTHFISH         NaN
 14                               PATAGONIAN TOOTHFISH         NaN
 15  FISH FILLETS 2/2 PART OF CONTAINER 74  TOTAL C...     30485.0
 16  FISH FILLETS 1/2 PART OF CONTAINER 375 CARTONS...     30485.0
 17  BOXES FROZEN FISH SHIPPER PROVIDED HS CODE  03...         NaN
 18  419 CARTONS: 12.254,09 KGS. CH ILEAN SEABASS H...         NaN
 19  FROZEN PATAGONIAN TOOTHFIS H HGT MSC CERTIFIE ...         NaN
 20  1405 BOXES WILD PINK PATAGONIANIQF HLSO 16/20 ...     30617.0
 21  PATAGONIAN TOOTHFISH(DISSOSTICHUS ELEGINOIDES)...     30383.0
 22  FROZEN H & G TAIL OFF PATAGONIAN TOOTHFISH NE ...         NaN
 23  1 CASE - 49,35 LBS NET WEIGHT FROZEN SEABAS FI...     30485.0
 24  NCM 03031100 FROZEN TOOTH FISH HGT WITHOUT COL...     30311.0
 25  NCM 03031100 FROZEN TOOTH FISH HGT WITHOUT COL...     30311.0
 26                               PATAGONIAN TOOTHFISH         NaN
 27                               PATAGONIAN TOOTHFISH         NaN
 28                GRAND WORLD CRUISE ANTARCTICA GUIDE         NaN
 29                                                NaN         NaN
 30                                                NaN         NaN
 31                                                NaN         NaN
 32                                                NaN         NaN
 33                                                NaN         NaN
 34                                                NaN         NaN
 35                                                NaN         NaN
 36                                                NaN         NaN
 37                                                NaN         NaN
 38                                                NaN         NaN
 39                                                NaN         NaN

                                       Marks & Numbers                    HS  \
 0                                            PESANTAR                 30383
 1                                            PESANTAR                 30383
 2                                            PESANTAR                 30383
 3        NO MARKS NO MARKS NO MARKS NO MARKS NO MARKS                 30481
 4                                            NO MARKS                 30485
 5                                            NO MARKS                 30383
 6                                            NO MARKS                 30383
 7                                            NO MARKS                 30383
 8                                            NO MARKS                 30383
 9                                            NO MARKS                 30383
 10                                           NO MARKS                 30383
 11                                           NO MARKS                 30383
 12                                           NO MARKS                 30383
 13                                                N/M                 30383
 14                                                M/N                 30383
 15                               NO MARKS . . . . . .                 30485
 16                       NO MARKS . . . . . . . . . .                 30485
 17  NO MARKS NO MARKS NO MARKS NO MARKS NO MARKS N...  030383 030489 030499
 18                                                N/M                 30485
 19                NO MARKS NO MARKS NO MARKS NO MARKS                 30383
 20                                           NO MARKS                 30617
 21                                           NO MARKS                 30383
 22       NO MARKS NO MARKS NO MARKS NO MARKS NO MARKS                 30383
 23                                           NO MARKS                 30485
 24                                           NO MARKS         030311 401140
 25                                           NO MARKS                 30311
 26                                                N/M                 30383
 27                                                N/M                 30383
 28                                           $250.00                 980000
 29                                                NaN                   NaN
 30                                                NaN                   NaN
 31                                                NaN                   NaN
 32                                                NaN                   NaN
 33                                                NaN                   NaN
 34                                                NaN                   NaN
 35                                                NaN                   NaN
 36                                                NaN                   NaN
 37                                                NaN                   NaN
 38                                                NaN                   NaN
 39                                                NaN                   NaN

      datetime
 0  2020-02-11
 1  2020-02-11
 2  2020-02-11
 3  2020-02-10
 4  2020-02-10
 5  2020-02-06
 6  2020-02-06
 7  2020-02-06
 8  2020-02-06
 9  2020-02-06
 10 2020-02-06
 11 2020-02-06
 12 2020-02-06
 13 2020-02-05
 14 2020-02-05
 15 2020-02-05
 16 2020-02-05
 17 2020-01-30
 18 2020-01-30
 19 2020-01-26
 20 2020-01-25
 21 2020-01-24
 22 2020-01-24
 23 2020-01-23
 24 2020-01-22
 25 2020-01-22
 26 2020-01-16
 27 2020-01-14
 28 2020-01-14
 29 2020-01-12
 30 2020-01-11
 31 2020-01-10
 32 2020-01-08
 33 2020-01-08
 34 2020-01-06
 35 2020-01-05
 36 2020-01-05
 37 2020-01-03
 38 2020-01-03
 39 2020-01-03  ,
 ['Date',
  'Shipper Declared',
  'Country of Origin',
  'Weight',
  'Port of Arrival',
  'datetime'])

In [74]:
Jan_df = monthly_data_df.loc[monthly_data_df["datetime"] == date,  columns]
Jan_df

ValueError: Lengths must match

In [ ]:
monthly_data_df['Shipper Declared']

In [ ]:
monthly_data_df['Shipper Declared']


monthly_data_df['Date']

In [ ]:
monthly_data['New_Date'] = pd.to_datetime(monthly_data['Date'], format='%d/%m/%Y')

In [ ]:
monthly_data["Shipper Declared"].unique()
total_players = monthly_data["Shipper Declared"].unique().shape[0]
total_players

In [ ]:
player = pd.DataFrame({ "Total Players": [total_players]})
    
player

In [ ]:
from datetime import datetime
datetime.strptime('07/28/2014', '%m/%d/%Y')

In [ ]:
date = pd.date_range('1/1/2020', '1/31/2020')
date

In [ ]:
price_male = monthly_data.loc[monthly_data["Date"] == '2020/3/1']
price_male

In [ ]:
df['UK Date'] = pd.to_datetime(monthly_data['Date'], format='%m/%d/%y')